[tool.poetry]
name = "cs371"
version = "0.1.0"
description = ""
authors = ["Jaeyoung <akqq24@kaist.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
